esversion: 2
updates:
  # Flutter/Dart dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "Fredericobarbosa"
    labels:
      - "dependencies"
      - "flutter"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "Fredericobarbosa"
    labels:
      - "dependencies"
      - "github-actions"