name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Analysis
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Analyze code
      run: flutter analyze --fatal-infos
      
    - name: Check for unused dependencies
      run: flutter pub deps --no-dev
      
    - name: Run security audit
      run: flutter pub audit
      
    - name: Generate coverage report
      run: |
        flutter test --coverage
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: coverage/lcov.info
        fail_ci_if_error: false